### PR TITLE
fix missing bracket in hcxlabtool help

### PR DESCRIPTION
**Pull request by gemesa**
While experimenting with `hcxlabtool` I noticed a missing bracket in the help section which I fixed:

```
$ hcxlabtool -h         
...
Legend
real time display:
 R = + AP is in TX range
 P = + got PMKID
 M = + AP display:     got EAPOL M1M2M3 (AUTHORIZATION)
 M = + CLIENT display: got EAPOL M1M2 (ROGUE CHALLENGE
 A = + AUTHENTICATION KEY MANAGEMENT PSK
...
```

'(ROGUE CHALLENGE' --> '(ROGUE CHALLENGE)'

### CODE REVIEW

**Comment by ZerBea** [comment]
Great, merged. Thanks again.

Some additional information:
After several test on hcxlabtool, I'm working on the final implementation of
rca scan (passive and active). If that is working as expected I'll replace
hcxdumptool by hcxlabtool code.
hcxlabtool is a hundred times more effective than hcxdumptool. Additional
it use the new NL80211 stack, active monitor and support a wide range of interfaces.

I guess, hcxdumptool 6.2.9 will be that last WIRELESS EXTENSION version.

These functions are not longer present in hcxlabtool, because they are slow:
the entire crypto stuff
soft coded filter lists
check driver (if rca scan is working, driver is working as expected)
check injection (if active rca scan is working, driver is working as expected)
server/client status mode
capture data traffic (will not work any longer, because we limit bandwidth to 20MHz) - user can run tshark in parallel to dump data traffic
RSSI evaluation (useless, because we are packet oriented - even if we are at -90dBm, if the target received our packet, the attack was successful)

**Comment by gemesa** [comment]
> soft coded filter lists

So `--do_targetscan` will not be available and we should use `--bpf=` right?

**Comment by ZerBea** [comment]
I'm undecided. Using a BPF is a 100% solution that save a lot of CPU cycles.
But it might be a little bit oversized regarding such a simple thing like a rca_scan.

Implementation of a rca_scan is mandatory, because it is very helpful when directing a DF-antenna to the target.

**Comment by ZerBea** [comment]
Directing a DF-antenna to a target is not simple. You have to take care about reflections, the Fresnel zone and interference from other transmitters.
Also it is a 2way process (the target must receive hcxlabtool's packet and hcxlabtool must receive a  packet coming from teh target).
Regarding this, RSSI, tx power of the interface, real antenna direction and tx power of the target is absolutely meaningless.

**Pull request merged**
